seo:
  site_name: Imageboost
  title: Imageboost
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#61543D'
  medium-text_color: '#A49886'
  light-text_color: '#ffffff'
  featured-text_color: '#424242'
  dark_color: '#A49886'
  less-dark_color: '#bdb5a8'
  medium_color: '#CEC6BB'
  light_color: '#E7E3DD'
  v-light_color: '#ffffff'
  featured_color: '#906554'
  accent_color: '#7E9081'
